package djk.procesardkj.view.inicio.consultas;

import com.toedter.calendar.JCalendar;
import djk.procesardkj.controller.ControllerGrupo;
import djk.procesardkj.domain.AnioLectivo;
import djk.procesardkj.domain.Grupo;
import djk.procesardkj.domain.Matricula;
import djk.procesardkj.view.ViewAdministrador;
import java.awt.Component;
import java.awt.Container;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class ViewConsultaGrados extends javax.swing.JInternalFrame {

    ControllerGrupo control;
    AnioLectivo anioLocal;

    public ViewConsultaGrados() {
        initComponents();
        iniciarControladores();

    }

    private void iniciarControladores() {
        control = new ControllerGrupo();
        anioLocal = ViewAdministrador.anioLectivo;
        botonConsultar.setEnabled(false);
        comboJornada.setEnabled(false);
        comboGrupo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelGrado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboGrados = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboJornada = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboGrupo = new javax.swing.JComboBox<>();
        botonConsultar = new javax.swing.JButton();
        botonLimpliar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoGrupo = new javax.swing.JTextField();
        textoDirector = new javax.swing.JTextField();
        textoSize = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consulta por grupos - estudiantes");
        setPreferredSize(new java.awt.Dimension(837, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelGrado.setBackground(new java.awt.Color(255, 255, 255));
        panelGrado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Grados");

        comboGrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion:", "Jardin", "Transicion", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Septimo", "Octavo", "Noveno", "Decimo", "Once" }));
        comboGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGradosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jornadas");

        comboJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion:", "Mañana", "Tarde", "Nocturna" }));
        comboJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJornadaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Grupos");

        comboGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGrupoActionPerformed(evt);
            }
        });

        botonConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/filtrar.png"))); // NOI18N
        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultar(evt);
            }
        });

        botonLimpliar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonLimpliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/varita-magica.png"))); // NOI18N
        botonLimpliar.setText("Limpiar");
        botonLimpliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpliar(evt);
            }
        });

        javax.swing.GroupLayout panelGradoLayout = new javax.swing.GroupLayout(panelGrado);
        panelGrado.setLayout(panelGradoLayout);
        panelGradoLayout.setHorizontalGroup(
            panelGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradoLayout.createSequentialGroup()
                .addGroup(panelGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(comboGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGradoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(panelGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGradoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelGradoLayout.createSequentialGroup()
                        .addComponent(comboJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(botonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(28, 28, 28)))
                .addComponent(botonLimpliar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGradoLayout.setVerticalGroup(
            panelGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultar)
                    .addComponent(botonLimpliar))
                .addContainerGap())
        );

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Grado:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Director de Grupo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nro Estudiantes:");

        textoGrupo.setEditable(false);
        textoGrupo.setForeground(new java.awt.Color(0, 102, 102));

        textoDirector.setEditable(false);
        textoDirector.setForeground(new java.awt.Color(0, 102, 102));

        textoSize.setEditable(false);
        textoSize.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textoDirector)))
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(textoSize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textoSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGradosActionPerformed
        if (comboGrados.getSelectedIndex() != 0) {
            comboJornada.setEnabled(true);
        } else {
            comboJornada.setEnabled(false);
            comboGrupo.setEnabled(false);
        }
        comboJornada.setSelectedIndex(0);
        eliminarItemComboGrupo();
    }//GEN-LAST:event_comboGradosActionPerformed

    private void comboJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJornadaActionPerformed
        eliminarItemComboGrupo();
        if (comboJornada.getSelectedIndex() != 0) {
            comboGrupo.setEnabled(true);
            cargarComboGrupos();
        } else {
            comboGrupo.setEnabled(false);
        }
    }//GEN-LAST:event_comboJornadaActionPerformed

    private void comboGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGrupoActionPerformed
        if (comboGrupo.getSelectedIndex() != 0) {
            botonConsultar.setEnabled(true);
        } else {
            botonConsultar.setEnabled(false);
        }
    }//GEN-LAST:event_comboGrupoActionPerformed

    private void botonConsultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultar
        botonConsultar();
    }//GEN-LAST:event_botonConsultar

    private void botonLimpliar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpliar
        botonLimpiar();
    }//GEN-LAST:event_botonLimpliar

    private void eliminarItemComboGrupo() {
        comboGrupo.removeAllItems();
        comboGrupo.addItem("Selec.");
    }

    private void cargarComboGrupos() {
        try {
            List<Grupo> grupos = getListaGrupos();
            grupos.forEach((g) -> {
                comboGrupo.addItem("" + g.getIndiceGrupo());
            });
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelDatos, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void botonLimpiar() {
        tabla.setModel(new DefaultTableModel());
        comboGrados.setSelectedIndex(0);
        comboGrupo.setSelectedIndex(0);
        comboJornada.setSelectedIndex(0);
        textoDirector.setText("");
        textoGrupo.setText("");
        textoSize.setText("");
        enableComponents(panelDatos, false);
    }

    private void botonConsultar() {
        int indice = comboGrupo.getSelectedIndex() - 1;

        try {
            Grupo grupo = getListaGrupos().get(indice);
            textoDirector.setText((grupo.getDocente() != null) ? grupo.getDocente().getNombreCarga() : "No disponible");
            textoGrupo.setText(grupo.toString());
            textoSize.setText("" + grupo.getMatriculaList().size());
            getTabla(grupo);
            enableComponents(panelGrado, true);
            enableComponents(panelDatos, true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelDatos, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
        }

    }

    private List<Grupo> getListaGrupos() throws Exception {
        int jornada = comboJornada.getSelectedIndex();
        int grupo = comboGrados.getSelectedIndex() - 1;
        return control.verGrupos(anioLocal.getIdAnioLectivo(), grupo, jornada);
    }

    public void enableComponents(Container container, boolean enable) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                enableComponents((Container) component, enable);
            }
        }
    }

    public void getTabla(Grupo grupo) throws Exception {
        String[] columnas = {"#", "TIPO ID", "IDENTIFICACION", "NOMBRE COMPLETO", "SEXO", "FECHA INGRESO"};
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(columnas);

        String[] fila = new String[columnas.length];
        int cont = 1;
        for (Matricula matricula : grupo.getMatriculaList()) {
            fila[0] = String.valueOf(cont);
            fila[1] = matricula.getEstudiante().getTipoIdTexto();
            fila[2] = matricula.getEstudiante().getIdentificacion();
            fila[3] = matricula.getEstudiante().getNombreCompleto();
            fila[4] = matricula.getEstudiante().getFechaIngresoTexto();
            fila[5] = matricula.getEstudiante().getFechaIngresoTexto();
            modelo.addRow(fila);
            cont++;
        }
        tabla.setModel(modelo);
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(modelo);
        tabla.setRowSorter(elQueOrdena);

        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tabla.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(60);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(400);
        columnModel.getColumn(4).setPreferredWidth(80);
        columnModel.getColumn(5).setPreferredWidth(80);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonLimpliar;
    private javax.swing.JComboBox<String> comboGrados;
    private javax.swing.JComboBox<String> comboGrupo;
    private javax.swing.JComboBox<String> comboJornada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelGrado;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textoDirector;
    private javax.swing.JTextField textoGrupo;
    private javax.swing.JTextField textoSize;
    // End of variables declaration//GEN-END:variables
}
