package djk.procesardkj.view.inicio;

import djk.procesardkj.view.inicio.ViewEstudianteResumen;
import com.toedter.calendar.JCalendar;
import djk.procesardkj.controller.ControllerEstudiante;
import djk.procesardkj.domain.Docente;
import djk.procesardkj.domain.Estudiante;
import djk.procesardkj.view.ViewAdministrador;
import java.awt.Component;
import java.awt.Container;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

public class ViewEstudiantes extends javax.swing.JInternalFrame {

    ControllerEstudiante control;
    final String ACTIVO = "Activo";

    public ViewEstudiantes() {
        initComponents();
        iniciarComponentes();
    }

    private void iniciarComponentes() {
        enableComponents(panelCreacion, false);
        control = new ControllerEstudiante();
        cargarTabla(ACTIVO);

    }

    private void cargarTabla(String estado) {
        try {
            tablaEstudiantes.setModel(control.getTabla(estado));
            tablaEstudiantes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumnModel columnModel = tablaEstudiantes.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(30);
            columnModel.getColumn(1).setPreferredWidth(120);
            columnModel.getColumn(2).setPreferredWidth(60);
            columnModel.getColumn(3).setPreferredWidth(70);
            columnModel.getColumn(4).setPreferredWidth(100);
            columnModel.getColumn(5).setPreferredWidth(100);
            columnModel.getColumn(6).setPreferredWidth(100);
            columnModel.getColumn(7).setPreferredWidth(100);
            columnModel.getColumn(8).setPreferredWidth(80);
            columnModel.getColumn(9).setPreferredWidth(80);
            columnModel.getColumn(10).setPreferredWidth(150);
            columnModel.getColumn(11).setPreferredWidth(100);
            columnModel.getColumn(12).setPreferredWidth(80);
            columnModel.getColumn(13).setPreferredWidth(120);
            columnModel.getColumn(14).setPreferredWidth(120);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        textoFiltro = new javax.swing.JTextField();
        comboFilter = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        panelCreacion = new javax.swing.JPanel();
        labelPrimerNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        texto1nombre = new javax.swing.JTextField();
        textoCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        texto2nombre = new javax.swing.JTextField();
        texto2Apellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboTipoId = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateNacimiento = new com.toedter.calendar.JDateChooser();
        textoIdentificacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dateExpedicion = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        textoLugarExpe = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        texto1Apellido = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jRadioOtro = new javax.swing.JRadioButton();
        jRadioFem = new javax.swing.JRadioButton();
        jRadioMasculino = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        comboTipoSangre = new javax.swing.JComboBox<>();
        labelFecha = new javax.swing.JLabel();
        textoId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        botonParientes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelCCPadre = new javax.swing.JLabel();
        labelCCMadre = new javax.swing.JLabel();
        jLabelCCPadre = new javax.swing.JLabel();
        jLabelCCMAdre = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Creacion y Modificacion de datos para Estudiantes");
        setPreferredSize(new java.awt.Dimension(1200, 640));

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setMinimumSize(new java.awt.Dimension(1200, 640));
        panelCentral.setPreferredSize(new java.awt.Dimension(1000, 640));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null), "Estudiantes creados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 225));

        tablaEstudiantes.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaEstudiantes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        panelCentral.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1160, -1));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/documento_1.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelCentral.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 150, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/editar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelCentral.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 150, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/basura.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelCentral.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, 150, -1));

        textoFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoFiltroKeyReleased(evt);
            }
        });
        panelCentral.add(textoFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 170, -1));

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Activo", "Suspendido", "Retirado" }));
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });
        panelCentral.add(comboFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 140, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Buscar");
        panelCentral.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        panelCreacion.setBackground(new java.awt.Color(255, 255, 255));
        panelCreacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelCreacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPrimerNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPrimerNombre.setText("1er Nombre:");
        panelCreacion.add(labelPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("1er Apellido:");
        panelCreacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
        panelCreacion.add(texto1nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 183, -1));
        panelCreacion.add(textoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 183, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("2do Nombre:");
        panelCreacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("2do Apellido:");
        panelCreacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));
        panelCreacion.add(texto2nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 183, -1));
        panelCreacion.add(texto2Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 183, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tipo Identificacion:");
        panelCreacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        comboTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "RC", "TI", "CC", "PASAPORTE" }));
        panelCreacion.add(comboTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("No. Identificacion:");
        panelCreacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Correo:");
        panelCreacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 50, -1));
        panelCreacion.add(dateNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 180, -1));
        panelCreacion.add(textoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 183, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Fecha de Expedicion:");
        panelCreacion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));
        panelCreacion.add(dateExpedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 180, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Lugar Expedicion: ");
        panelCreacion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));
        panelCreacion.add(textoLugarExpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, 183, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Id Estudiante:");
        panelCreacion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Fecha de Nacimiento:");
        panelCreacion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));
        panelCreacion.add(texto1Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 183, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jRadioOtro.setBackground(new java.awt.Color(255, 102, 255));
        jRadioOtro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioOtro.setText("Otro");

        jRadioFem.setBackground(new java.awt.Color(153, 153, 255));
        jRadioFem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioFem.setText("Femenino");

        jRadioMasculino.setBackground(new java.awt.Color(102, 204, 255));
        jRadioMasculino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioMasculino.setText("Masculino");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioFem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioOtro)
                    .addComponent(jRadioFem)
                    .addComponent(jRadioMasculino))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        panelCreacion.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 60));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Direccion:");
        panelCreacion.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        panelCreacion.add(textoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 183, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Sangre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        comboTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "O negativo (O-)", "O positivo (O+)", "A positivo (A +)", "A negativo (A-)", "B positivo (B +)", "B negativo (B-)", "AB negativo (AB-)", "AB positivo (AB+)" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboTipoSangre, 0, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCreacion.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 200, 60));

        labelFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(0, 153, 51));
        labelFecha.setText("yyyy-MM-dd");
        panelCreacion.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        textoId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoId.setForeground(new java.awt.Color(204, 0, 51));
        textoId.setText("0");
        panelCreacion.add(textoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Feha Ingreso:");
        panelCreacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/controlar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelCreacion.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 190, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/varita-magica.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelCreacion.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 190, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Parientes:");
        panelCreacion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        botonParientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonParientes.setText("+");
        botonParientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParientesActionPerformed(evt);
            }
        });
        panelCreacion.add(botonParientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 70, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de los padres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelCCPadre.setForeground(new java.awt.Color(204, 0, 0));
        labelCCPadre.setText("-----------------------");

        labelCCMadre.setForeground(new java.awt.Color(204, 0, 0));
        labelCCMadre.setText("-----------------------");

        jLabelCCPadre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCCPadre.setText("CC Padre:");

        jLabelCCMAdre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCCMAdre.setText("CC Madre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCCPadre)
                    .addComponent(jLabelCCMAdre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCCPadre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCCMadre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCCPadre)
                    .addComponent(jLabelCCPadre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCCMadre)
                    .addComponent(jLabelCCMAdre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCreacion.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 270, 80));

        panelCentral.add(panelCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 1150, 320));

        botonConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/busqueda.png"))); // NOI18N
        botonConsultar.setText("CONSULTAR");
        botonConsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        botonConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        panelCentral.add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        botonNuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        botonModificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        enableComponents(panelCreacion, false);
        limpiarCampos();
        botonEliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void textoFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoFiltroKeyReleased
        filtro(textoFiltro.getText().toUpperCase(), tablaEstudiantes);
    }//GEN-LAST:event_textoFiltroKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (btnGuardar.getText().equals("MODIFICAR")) {
            modificar();
        } else {
            botonGuardar();
        }

        cargarTabla(ACTIVO);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
        enableComponents(panelCreacion, false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        int opc = comboFilter.getSelectedIndex();
        //cargarTabla(opc);
    }//GEN-LAST:event_comboFilterActionPerformed

    private void botonParientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParientesActionPerformed

    }//GEN-LAST:event_botonParientesActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        botonConsultar();
    }//GEN-LAST:event_botonConsultarActionPerformed
    private void botonEliminar() {
        int codigo = seleccionTablaCodigo();

        if (codigo != -1) {
            if (JOptionPane.showConfirmDialog(rootPane, "Seguro que desea eliminar al Estudiante?",
                    "AVISO", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    control.eliminar(codigo);
                    JOptionPane.showMessageDialog(panelCentral, "Docente eliminado exitosamente.",
                            "Informacion", JOptionPane.INFORMATION_MESSAGE, frameIcon);
                    cargarTabla(ACTIVO);
                } catch (NullPointerException ex) {
                    JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion",
                            JOptionPane.WARNING_MESSAGE);
                }

            }

        }
    }

    private void botonConsultar() {
        int codigo = seleccionTablaCodigo();
        if (codigo != -1) {
            Estudiante estudiante;
            try {
                estudiante = control.buscarPorCodigo(codigo);
                ViewEstudianteResumen resumen = new ViewEstudianteResumen(estudiante);
                ViewAdministrador.escritorio.add(resumen);
                resumen.toFront();
                resumen.show();
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
            }

        }
    }

    private void modificar() {
        try {
            Estudiante estudiante = obtenerCamposActualizar();
            control.actualizar(estudiante);
            JOptionPane.showMessageDialog(panelCentral, "Estudiante modificado exitosamente.",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            enableComponents(panelCreacion, false);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void botonNuevo() {
        enableComponents(panelCreacion, true);
        textoId.setEnabled(true);
        btnGuardar.setText("GUARDAR");
        Date fechaActual = new JCalendar().getDate();
        labelFecha.setText(formatFecha(fechaActual));
    }

    private void botonModificar() {
        int codigo = seleccionTablaCodigo();
        if (codigo != -1) {
            enableComponents(panelCreacion, true);
            btnGuardar.setText("MODIFICAR");
            textoIdentificacion.setEnabled(false);
            Estudiante estudiante;
            try {
                estudiante = control.buscarPorCodigo(codigo);
                pintarCampos(estudiante);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
            }

        }
    }

    private int seleccionTablaCodigo() {
        int indice = tablaEstudiantes.getSelectedRow();
        if (indice == -1) {
            JOptionPane.showMessageDialog(panelCentral, "Seleccione un estudiante!", "Validacion", JOptionPane.INFORMATION_MESSAGE);
            return -1;
        } else {
            String codigo = String.valueOf(tablaEstudiantes.getValueAt(indice, 0));
            int cod = Integer.valueOf(codigo);
            return cod;
        }
    }

    private void botonGuardar() {
        if (validarCampos()) {
            Estudiante estudiante = obtenerCampos();
            try {
                control.registrar(estudiante);
                JOptionPane.showMessageDialog(panelCentral, "Estudiante registrado exitosamente.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                enableComponents(panelCreacion, false);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panelCentral, "Verifique los campos", "Validacion", JOptionPane.QUESTION_MESSAGE);
        }

    }

    public Estudiante obtenerCampos() {
        String identificacion = textoIdentificacion.getText();
        String primerNombre = texto1nombre.getText();
        String primerApellido = texto1Apellido.getText();
        String segundoNombre = texto2nombre.getText();
        String segundoApellido = texto2Apellido.getText();
        int tipoId = comboTipoId.getSelectedIndex();
        String direccion = textoDireccion.getText();
        int sexo = getRadioSexo();
        String correo = textoCorreo.getText();
        Date fechaExpedicion = null;
        Date fechaNacimiento = null;
        try {
            fechaExpedicion = dateExpedicion.getDate();
            fechaNacimiento = dateNacimiento.getDate();
        } catch (Exception e) {
            //Pendiente   
        }

        String lugarExpedicion = textoLugarExpe.getText();
        int tipoSagre = comboTipoSangre.getSelectedIndex();
        Date fechaIngreso = new JCalendar().getDate();

        Estudiante estudiante = new Estudiante(identificacion, tipoId, ACTIVO, fechaExpedicion, primerNombre, segundoNombre,
                primerApellido, segundoApellido, sexo, fechaNacimiento, direccion, tipoSagre, fechaIngreso, correo, lugarExpedicion);

        return estudiante;
    }

    private int getRadioSexo() {
        if (jRadioMasculino.isSelected()) {
            return 1;
        } else if (jRadioFem.isSelected()) {
            return 2;
        } else if (jRadioOtro.isSelected()) {
            return 3;
        } else {
            return 0;
        }
    }

    private void setRadioSexo(int numero) {
        switch (numero) {
            case 1:
                jRadioMasculino.setSelected(true);
            case 2:
                jRadioFem.setSelected(true);
            case 3:
                jRadioOtro.setSelected(true);
        }
    }

    private String formatFecha(Date fecha) {
        SimpleDateFormat objSDF = new SimpleDateFormat("yyyy-MM-dd");
        return objSDF.format(fecha);
    }

    private Estudiante obtenerCamposActualizar() {
        int codigo = Integer.parseInt(textoId.getText());

        try {
            Estudiante estudiante = control.buscarPorCodigo(codigo);
            System.out.println(estudiante.toString());
            estudiante.setPrimerApellido(texto1Apellido.getText());
            estudiante.setSegundoApellido(texto2Apellido.getText());
            estudiante.setPrimerNombre(texto1nombre.getText());
            estudiante.setSegundoNombre(texto2nombre.getText());
            estudiante.setTipoId(comboTipoId.getSelectedIndex());
            estudiante.setDireccion(textoDireccion.getText());
            estudiante.setSexo(getRadioSexo());
            estudiante.setCorreo(textoCorreo.getText());

            Date fechaExpedicion = null;
            Date fechaNacimiento = null;
            try {
                fechaExpedicion = dateExpedicion.getDate();
                fechaNacimiento = dateNacimiento.getDate();
            } catch (Exception e) {
            }
            estudiante.setFechaNacimiento(fechaNacimiento);
            estudiante.setExpedicion(fechaExpedicion);
            estudiante.setLugarExpedicion(textoLugarExpe.getText());
            estudiante.setTipoSangre(comboTipoSangre.getSelectedIndex());
            return estudiante;
        } catch (Exception ex) {
            return null;
        }
    }

    private void pintarCampos(Estudiante estudiante) {
        textoId.setText(estudiante.getIdEstudiante().toString());
        textoIdentificacion.setText(estudiante.getIdentificacion());
        texto1nombre.setText(estudiante.getPrimerNombre());
        texto2nombre.setText(estudiante.getSegundoNombre());
        texto1Apellido.setText(estudiante.getPrimerApellido());
        texto2Apellido.setText(estudiante.getSegundoApellido());
        comboTipoId.setSelectedIndex(estudiante.getTipoId());//pendiente
        textoDireccion.setText(estudiante.getDireccion());
        setRadioSexo(estudiante.getSexo());
        textoCorreo.setText(estudiante.getDireccion());
        dateExpedicion.setDate(estudiante.getExpedicion());
        dateNacimiento.setDate(estudiante.getFechaNacimiento());
        textoLugarExpe.setText(estudiante.getLugarExpedicion());
        comboTipoSangre.setSelectedIndex(estudiante.getTipoId());
        labelFecha.setText(estudiante.getFechaIngresoTexto());
    }

    private boolean validarCampos() {

//        if (textoId.getText().equals("")) {
//            return false;
//        }
//        if (textoNombre.getText().equals("")) {
//            return false;
//        }
//        if (textoApellidos.getText().equals("")) {
//            return false;
//        }
//        if (pass.getText().equals("")) {
//            return false;
//        }
//        try {
//            if (calendarFecha.getDate() == null) {
//                return false;
//            }
//        } catch (Exception e) {
//            return false;
//        }
        return true;
    }

    private void limpiarCampos() {
        textoId.setText("");
        textoIdentificacion.setText("");
        texto1nombre.setText("");
        texto2nombre.setText("");
        texto1Apellido.setText("");
        texto2Apellido.setText("");
        comboTipoId.setSelectedIndex(0);
        textoDireccion.setText("");
        setRadioSexo(0);
        textoCorreo.setText("");
        dateExpedicion.setDate(null);
        dateNacimiento.setDate(null);
        textoLugarExpe.setText("");
        comboTipoSangre.setSelectedIndex(0);
        labelFecha.setText("");
    }

    public void enableComponents(Container container, boolean enable) {

        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                enableComponents((Container) component, enable);
            }
        }
    }

    private void filtro(String consulta, JTable jtableBuscar) {
        DefaultTableModel dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonParientes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JComboBox<String> comboTipoId;
    private javax.swing.JComboBox<String> comboTipoSangre;
    private com.toedter.calendar.JDateChooser dateExpedicion;
    private com.toedter.calendar.JDateChooser dateNacimiento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCCMAdre;
    private javax.swing.JLabel jLabelCCPadre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioFem;
    private javax.swing.JRadioButton jRadioMasculino;
    private javax.swing.JRadioButton jRadioOtro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCCMadre;
    private javax.swing.JLabel labelCCPadre;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelPrimerNombre;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelCreacion;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JTextField texto1Apellido;
    private javax.swing.JTextField texto1nombre;
    private javax.swing.JTextField texto2Apellido;
    private javax.swing.JTextField texto2nombre;
    private javax.swing.JTextField textoCorreo;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoFiltro;
    private javax.swing.JLabel textoId;
    private javax.swing.JTextField textoIdentificacion;
    private javax.swing.JTextField textoLugarExpe;
    // End of variables declaration//GEN-END:variables
}
