
package djk.procesardkj.view.inicio;

import djk.procesardkj.domain.Estudiante;

public class ViewEstudianteResumen extends javax.swing.JInternalFrame {

    public ViewEstudianteResumen() {
        initComponents();
    }

    public ViewEstudianteResumen(Estudiante estudiante) {
        initComponents();
        pintarCampos(estudiante);
    }
    
    private void pintarCampos(Estudiante e){
        txtIdentificacionEstudiante.setText(e.getIdentificacion());
        txtTipoIdEstudiante.setText(e.getTipoIdTexto());
        txtPrimerNombreEstudiante.setText(e.getPrimerNombre());
        txtSegundoNombreEstudiante.setText(e.getSegundoNombre());
        txtPrimerApellidoEstudiante.setText(e.getPrimerApellido());
        txtSegundoApellidoEstudiante.setText(e.getSegundoApellido());
        txtCorreoEstudiante.setText(e.getCorreo());
        txtDireccionEstudiante.setText(e.getDireccion());
        txtFechaExpedicionEstudiante.setText(e.getExpedicionTexto());
        txtFechaIngresoEstudiante.setText(e.getFechaIngresoTexto());
        txtFechaNacimientoEstudiante.setText(e.getFechaNacimientoTexto());
        txtTipoSangreEstudiante.setText(e.getTipoSangreTexto());
        txtSexoEstudiante.setText(e.getSexoTexto());
        txtLugarExpedicionEstudiante.setText(e.getLugarExpedicion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDatosEstudiante = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtFechaIngresoEstudiante = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelPrimerNombreEstudiante = new javax.swing.JLabel();
        txtPrimerNombreEstudiante = new javax.swing.JLabel();
        txtDireccionEstudiante = new javax.swing.JLabel();
        txtPrimerApellidoEstudiante = new javax.swing.JLabel();
        txtSegundoApellidoEstudiante = new javax.swing.JLabel();
        txtCorreoEstudiante = new javax.swing.JLabel();
        txtTipoSangreEstudiante = new javax.swing.JLabel();
        txtTipoIdEstudiante = new javax.swing.JLabel();
        txtSegundoNombreEstudiante = new javax.swing.JLabel();
        txtIdentificacionEstudiante = new javax.swing.JLabel();
        txtFechaExpedicionEstudiante = new javax.swing.JLabel();
        txtLugarExpedicionEstudiante = new javax.swing.JLabel();
        txtFechaNacimientoEstudiante = new javax.swing.JLabel();
        txtSexoEstudiante = new javax.swing.JLabel();
        panelDatosPadre = new javax.swing.JPanel();
        labelNombresPadre = new javax.swing.JLabel();
        labelApellidosPadre = new javax.swing.JLabel();
        labelTipoIdPadre = new javax.swing.JLabel();
        labelIdPadre = new javax.swing.JLabel();
        labelCorreoPadre = new javax.swing.JLabel();
        labelTelefonoPadre = new javax.swing.JLabel();
        txtTipoIdPadre = new javax.swing.JLabel();
        txtApellidosPadre = new javax.swing.JLabel();
        txtCorreoPadre = new javax.swing.JLabel();
        txtIdPadres = new javax.swing.JLabel();
        txtTelefonoPadre = new javax.swing.JLabel();
        txtNombresPadre = new javax.swing.JLabel();
        panelDatosMadre = new javax.swing.JPanel();
        labelPrimerNombre2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtTelefonoMadre = new javax.swing.JLabel();
        txtIdMadre = new javax.swing.JLabel();
        txtApellidosMadre = new javax.swing.JLabel();
        txtNombresMadre = new javax.swing.JLabel();
        txtCorreoMadre = new javax.swing.JLabel();
        txtTipoIdMadre = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatosEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 51), null), "Datos del estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        panelDatosEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("1er Apellido:");
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("2do Nombre:");
        panelDatosEstudiante.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("2do Apellido:");
        panelDatosEstudiante.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tipo Identificacion:");
        panelDatosEstudiante.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("No. Identificacion:");
        panelDatosEstudiante.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 113, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Correo:");
        panelDatosEstudiante.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Fecha de Expedicion:");
        panelDatosEstudiante.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Lugar Expedicion: ");
        panelDatosEstudiante.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Fecha de Nacimiento:");
        panelDatosEstudiante.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Tipo Sangre:");
        panelDatosEstudiante.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        txtFechaIngresoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaIngresoEstudiante.setForeground(new java.awt.Color(0, 153, 51));
        txtFechaIngresoEstudiante.setText("yyyy-MM-dd");
        txtFechaIngresoEstudiante.setPreferredSize(new java.awt.Dimension(48, 15));
        panelDatosEstudiante.add(txtFechaIngresoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Feha Ingreso:");
        panelDatosEstudiante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Direccion:");
        jLabel20.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Sexo:");
        panelDatosEstudiante.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 80, -1));

        labelPrimerNombreEstudiante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPrimerNombreEstudiante.setText("1er Nombre:");
        labelPrimerNombreEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(labelPrimerNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        txtPrimerNombreEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrimerNombreEstudiante.setText("1er Nombre:");
        txtPrimerNombreEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtPrimerNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, -1));

        txtDireccionEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDireccionEstudiante.setText("Direccion:");
        txtDireccionEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtDireccionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, -1));

        txtPrimerApellidoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrimerApellidoEstudiante.setText("1er Apellido:");
        txtPrimerApellidoEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtPrimerApellidoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        txtSegundoApellidoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSegundoApellidoEstudiante.setText("2do Apellido:");
        txtSegundoApellidoEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtSegundoApellidoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 150, -1));

        txtCorreoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreoEstudiante.setText("Correo:");
        txtCorreoEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtCorreoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        txtTipoSangreEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTipoSangreEstudiante.setText("Tipo Sangre:");
        txtTipoSangreEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtTipoSangreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 150, -1));

        txtTipoIdEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTipoIdEstudiante.setText("Tipo de identificacion:");
        panelDatosEstudiante.add(txtTipoIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, -1));

        txtSegundoNombreEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSegundoNombreEstudiante.setText("2do Nombre:");
        txtSegundoNombreEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtSegundoNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 150, -1));

        txtIdentificacionEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdentificacionEstudiante.setText("No. Identificacion:");
        txtIdentificacionEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtIdentificacionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, -1));

        txtFechaExpedicionEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaExpedicionEstudiante.setText("Fecha de Expedicion:");
        txtFechaExpedicionEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtFechaExpedicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 140, -1));

        txtLugarExpedicionEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLugarExpedicionEstudiante.setText("Lugar Expedicion: ");
        txtLugarExpedicionEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtLugarExpedicionEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 160, -1));

        txtFechaNacimientoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaNacimientoEstudiante.setText("Fecha de Nacimiento:");
        txtFechaNacimientoEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtFechaNacimientoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 150, -1));

        txtSexoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSexoEstudiante.setText("Sexo:");
        txtSexoEstudiante.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosEstudiante.add(txtSexoEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 150, -1));

        jPanel1.add(panelDatosEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 937, 192));

        panelDatosPadre.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosPadre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null), "Datos del padre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        panelDatosPadre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombresPadre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombresPadre.setText("Nombres:");
        panelDatosPadre.add(labelNombresPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        labelApellidosPadre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelApellidosPadre.setText("Apellidos:");
        panelDatosPadre.add(labelApellidosPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        labelTipoIdPadre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTipoIdPadre.setText("Tipo identificacion:");
        panelDatosPadre.add(labelTipoIdPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelIdPadre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelIdPadre.setText("No. Identificacion:");
        panelDatosPadre.add(labelIdPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 113, -1));

        labelCorreoPadre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCorreoPadre.setText("Correo:");
        panelDatosPadre.add(labelCorreoPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        labelTelefonoPadre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTelefonoPadre.setText("Telefono:");
        panelDatosPadre.add(labelTelefonoPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtTipoIdPadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTipoIdPadre.setText("Tipo identificacion");
        panelDatosPadre.add(txtTipoIdPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 150, -1));

        txtApellidosPadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApellidosPadre.setText("Apellidos:");
        panelDatosPadre.add(txtApellidosPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 190, -1));

        txtCorreoPadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreoPadre.setText("Correo:");
        panelDatosPadre.add(txtCorreoPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 190, -1));

        txtIdPadres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdPadres.setText("No. Identificacion:");
        panelDatosPadre.add(txtIdPadres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, -1));

        txtTelefonoPadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefonoPadre.setText("Telefono:");
        panelDatosPadre.add(txtTelefonoPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, -1));

        txtNombresPadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombresPadre.setText("Nombres:");
        panelDatosPadre.add(txtNombresPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, -1));

        jPanel1.add(panelDatosPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 380, 210));

        panelDatosMadre.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosMadre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null), "Datos de la madre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        panelDatosMadre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPrimerNombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPrimerNombre2.setText("Nombres:");
        panelDatosMadre.add(labelPrimerNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Apellidos:");
        panelDatosMadre.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Tipo identificacion:");
        jLabel27.setPreferredSize(new java.awt.Dimension(120, 15));
        panelDatosMadre.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("No. Identificacion:");
        panelDatosMadre.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 113, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Correo:");
        panelDatosMadre.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Telefono:");
        panelDatosMadre.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtTelefonoMadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefonoMadre.setText("Telefono:");
        panelDatosMadre.add(txtTelefonoMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, -1));

        txtIdMadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdMadre.setText("No. Identificacion:");
        panelDatosMadre.add(txtIdMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        txtApellidosMadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApellidosMadre.setText("Apellidos:");
        panelDatosMadre.add(txtApellidosMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 200, -1));

        txtNombresMadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombresMadre.setText("Nombres:");
        panelDatosMadre.add(txtNombresMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 200, -1));

        txtCorreoMadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreoMadre.setText("Correo:");
        panelDatosMadre.add(txtCorreoMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));

        txtTipoIdMadre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTipoIdMadre.setText("Tipo identificacion:");
        panelDatosMadre.add(txtTipoIdMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, -1));

        jPanel1.add(panelDatosMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 380, 210));

        botonCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonCerrar.setText("CERRAR");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HOJA DE VIDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("IMPRIMIR");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApellidosPadre;
    private javax.swing.JLabel labelCorreoPadre;
    private javax.swing.JLabel labelIdPadre;
    private javax.swing.JLabel labelNombresPadre;
    private javax.swing.JLabel labelPrimerNombre2;
    private javax.swing.JLabel labelPrimerNombreEstudiante;
    private javax.swing.JLabel labelTelefonoPadre;
    private javax.swing.JLabel labelTipoIdPadre;
    private javax.swing.JPanel panelDatosEstudiante;
    private javax.swing.JPanel panelDatosMadre;
    private javax.swing.JPanel panelDatosPadre;
    private javax.swing.JLabel txtApellidosMadre;
    private javax.swing.JLabel txtApellidosPadre;
    private javax.swing.JLabel txtCorreoEstudiante;
    private javax.swing.JLabel txtCorreoMadre;
    private javax.swing.JLabel txtCorreoPadre;
    private javax.swing.JLabel txtDireccionEstudiante;
    private javax.swing.JLabel txtFechaExpedicionEstudiante;
    private javax.swing.JLabel txtFechaIngresoEstudiante;
    private javax.swing.JLabel txtFechaNacimientoEstudiante;
    private javax.swing.JLabel txtIdMadre;
    private javax.swing.JLabel txtIdPadres;
    private javax.swing.JLabel txtIdentificacionEstudiante;
    private javax.swing.JLabel txtLugarExpedicionEstudiante;
    private javax.swing.JLabel txtNombresMadre;
    private javax.swing.JLabel txtNombresPadre;
    private javax.swing.JLabel txtPrimerApellidoEstudiante;
    private javax.swing.JLabel txtPrimerNombreEstudiante;
    private javax.swing.JLabel txtSegundoApellidoEstudiante;
    private javax.swing.JLabel txtSegundoNombreEstudiante;
    private javax.swing.JLabel txtSexoEstudiante;
    private javax.swing.JLabel txtTelefonoMadre;
    private javax.swing.JLabel txtTelefonoPadre;
    private javax.swing.JLabel txtTipoIdEstudiante;
    private javax.swing.JLabel txtTipoIdMadre;
    private javax.swing.JLabel txtTipoIdPadre;
    private javax.swing.JLabel txtTipoSangreEstudiante;
    // End of variables declaration//GEN-END:variables
}
