/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package djk.procesardkj.view.inicio;

/**
 *
 * @author ENOR ACOSTA
 */
public class ViewPadres extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewPadres
     */
    public ViewPadres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDatosMadre = new javax.swing.JPanel();
        labelPrimerNombre1 = new javax.swing.JLabel();
        textoNombreMadre = new javax.swing.JTextField();
        textoCorreoMadre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textoApellidoMadre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        comboTipoIdMadre = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textoIdentificacionMadre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textoTelefonoMadre = new javax.swing.JTextField();
        panelDatosPadre = new javax.swing.JPanel();
        labelPrimerNombre = new javax.swing.JLabel();
        textonombrePadre = new javax.swing.JTextField();
        textoCorreoPadre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textoApellidosPadre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboTipoIdPadre = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textoIdentificacionPadre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textoTelefonoPadre = new javax.swing.JTextField();

        panelDatosMadre.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosMadre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null), "Datos de la madre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelDatosMadre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPrimerNombre1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPrimerNombre1.setText("Nombres:");
        panelDatosMadre.add(labelPrimerNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        panelDatosMadre.add(textoNombreMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 183, -1));
        panelDatosMadre.add(textoCorreoMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 183, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Apellidos:");
        panelDatosMadre.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        panelDatosMadre.add(textoApellidoMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 183, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Tipo de identificacion:");
        panelDatosMadre.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        comboTipoIdMadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "TI", "CC", "PASAPORTE" }));
        panelDatosMadre.add(comboTipoIdMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("No. Identificacion:");
        panelDatosMadre.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 113, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Correo:");
        panelDatosMadre.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));
        panelDatosMadre.add(textoIdentificacionMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 183, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Telefono:");
        panelDatosMadre.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        panelDatosMadre.add(textoTelefonoMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 183, -1));

        panelDatosPadre.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosPadre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null), "Datos del padre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelDatosPadre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPrimerNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPrimerNombre.setText("Nombres:");
        panelDatosPadre.add(labelPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        panelDatosPadre.add(textonombrePadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 183, -1));
        panelDatosPadre.add(textoCorreoPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 183, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Apellidos:");
        panelDatosPadre.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        panelDatosPadre.add(textoApellidosPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 183, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tipo de identificacion:");
        panelDatosPadre.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        comboTipoIdPadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "TI", "CC", "PASAPORTE" }));
        panelDatosPadre.add(comboTipoIdPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("No. Identificacion:");
        panelDatosPadre.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 113, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Correo:");
        panelDatosPadre.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));
        panelDatosPadre.add(textoIdentificacionPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 183, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Telefono:");
        panelDatosPadre.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        panelDatosPadre.add(textoTelefonoPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 183, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatosMadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(panelDatosPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDatosMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipoIdMadre;
    private javax.swing.JComboBox<String> comboTipoIdPadre;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPrimerNombre;
    private javax.swing.JLabel labelPrimerNombre1;
    private javax.swing.JPanel panelDatosMadre;
    private javax.swing.JPanel panelDatosPadre;
    private javax.swing.JTextField textoApellidoMadre;
    private javax.swing.JTextField textoApellidosPadre;
    private javax.swing.JTextField textoCorreoMadre;
    private javax.swing.JTextField textoCorreoPadre;
    private javax.swing.JTextField textoIdentificacionMadre;
    private javax.swing.JTextField textoIdentificacionPadre;
    private javax.swing.JTextField textoNombreMadre;
    private javax.swing.JTextField textoTelefonoMadre;
    private javax.swing.JTextField textoTelefonoPadre;
    private javax.swing.JTextField textonombrePadre;
    // End of variables declaration//GEN-END:variables
}
