package djk.procesardkj.view.inicio;

import djk.procesardkj.controller.ControllerDocente;
import djk.procesardkj.domain.Docente;
import djk.procesardkj.domain.Usuario;
import java.awt.Component;
import java.awt.Container;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class ViewDocente extends javax.swing.JInternalFrame {

    ControllerDocente control;

    public ViewDocente() {
        initComponents();
        iniciarComponentes();
    }

    private void iniciarComponentes() {
        enableComponents(panelCreacion, false);
        control = new ControllerDocente();
        cargarTabla(0);

    }

    private void cargarTabla(int numero) {
        Runnable proceso = new Runnable() {
            @Override
            public void run() {
                try {
                    DefaultTableModel modelo = control.getTabla(numero);
                    table.setModel(modelo);

                    TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(modelo);
                    table.setRowSorter(elQueOrdena);

                    table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                    TableColumnModel columnModel = table.getColumnModel();
                    columnModel.getColumn(0).setPreferredWidth(30);
                    columnModel.getColumn(1).setPreferredWidth(150);
                    columnModel.getColumn(2).setPreferredWidth(180);
                    columnModel.getColumn(3).setPreferredWidth(100);
                    columnModel.getColumn(4).setPreferredWidth(100);
                    columnModel.getColumn(5).setPreferredWidth(100);
                    columnModel.getColumn(6).setPreferredWidth(100);
                    columnModel.getColumn(7).setPreferredWidth(100);
                    columnModel.getColumn(8).setPreferredWidth(180);
                    columnModel.getColumn(9).setPreferredWidth(150);
                    columnModel.getColumn(10).setPreferredWidth(150);

                } catch (NullPointerException ex) {
                    JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
                }
            }
        };
        Thread hilo = new Thread(proceso);
        hilo.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelCreacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textoId = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textoApellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textoCiudad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        comboTipoSangre = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        labelCodigo = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JTextField();
        calendarFecha = new com.toedter.calendar.JDateChooser();
        textoFiltro = new javax.swing.JTextField();
        comboFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Creacion y Modificacion de datos para Docentes");
        setPreferredSize(new java.awt.Dimension(1200, 640));

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setMinimumSize(new java.awt.Dimension(1200, 640));
        panelCentral.setPreferredSize(new java.awt.Dimension(1000, 640));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null), "Docentes creados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 225));

        table.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        panelCentral.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1160, -1));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/documento_1.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelCentral.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 160, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/editar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelCentral.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 170, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/basura.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelCentral.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, 150, -1));

        panelCreacion.setBackground(new java.awt.Color(255, 255, 255));
        panelCreacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null), "Creacion/Modificacion de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelCreacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Identificacion:");
        panelCreacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellidos:");
        panelCreacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombres:");
        panelCreacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Estado:");
        panelCreacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        textoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIdActionPerformed(evt);
            }
        });
        panelCreacion.add(textoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 243, -1));
        panelCreacion.add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 242, -1));

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion:", "Activo", "Suspendido", "Retirado" }));
        panelCreacion.add(comboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 242, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/controlar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelCreacion.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 200, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/varita-magica.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelCreacion.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento:");
        panelCreacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de Sangre:   RH");
        panelCreacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, -1));
        panelCreacion.add(textoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 242, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Correo:");
        panelCreacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        panelCreacion.add(textoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 240, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Telefono:");
        panelCreacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        textoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTituloActionPerformed(evt);
            }
        });
        panelCreacion.add(textoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 243, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Ciudad:");
        panelCreacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Direccion:");
        panelCreacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        textoCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCiudadActionPerformed(evt);
            }
        });
        panelCreacion.add(textoCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 243, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Titulo:");
        panelCreacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 50, -1));

        textoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTelefonoActionPerformed(evt);
            }
        });
        panelCreacion.add(textoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 243, -1));

        comboTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "O negativo (O-)", "O positivo (O+)", "A positivo (A +)", "A negativo (A-)", "B positivo (B +)", "B negativo (B-)", "AB negativo (AB-)", "AB positivo (AB+)" }));
        panelCreacion.add(comboTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 190, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Contraseña:");
        panelCreacion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));
        panelCreacion.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 240, -1));

        labelCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCodigo.setText("0");
        panelCreacion.add(labelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 40, -1));

        textoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCorreoActionPerformed(evt);
            }
        });
        panelCreacion.add(textoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 243, -1));
        panelCreacion.add(calendarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 160, -1));

        panelCentral.add(panelCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 880, 290));

        textoFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoFiltroKeyReleased(evt);
            }
        });
        panelCentral.add(textoFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 210, -1));

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Activo", "Suspendido", "Retirado" }));
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });
        panelCentral.add(comboFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/imgDocente_1.png"))); // NOI18N
        panelCentral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 260, 280));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setText("BUSCAR:");
        panelCentral.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 1244, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        enableComponents(panelCreacion, true);
        textoId.setEnabled(true);
        btnGuardar.setText("GUARDAR");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        botonModificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        enableComponents(panelCreacion, false);
        limpiarCampos();
        botonEliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void textoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIdActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (btnGuardar.getText().equals("MODIFICAR")) {
            modificar();

        } else {
            botonGuardar();
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
        enableComponents(panelCreacion, false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void textoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTituloActionPerformed

    private void textoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCorreoActionPerformed

    private void textoCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCiudadActionPerformed

    private void textoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTelefonoActionPerformed

    private void textoFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoFiltroKeyReleased
        filtro(textoFiltro.getText().toUpperCase(), table);
    }//GEN-LAST:event_textoFiltroKeyReleased

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        int opc = comboFilter.getSelectedIndex();
        cargarTabla(opc);
    }//GEN-LAST:event_comboFilterActionPerformed
    private void botonEliminar() {
        int codigo = seleccionTablaCodigo();

        if (codigo != -1) {
            if (JOptionPane.showConfirmDialog(rootPane, "Seguro que desea eliminar el Docente?",
                    "AVISO", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    control.eliminar(codigo);
                    JOptionPane.showMessageDialog(panelCentral, "Docente eliminado exitosamente.",
                            "Informacion", JOptionPane.INFORMATION_MESSAGE, frameIcon);
                    cargarTabla(0);
                } catch (NullPointerException ex) {
                    JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion",
                            JOptionPane.WARNING_MESSAGE);
                }

            }

        }
    }

    private void modificar() {
        try {
            Docente docente = obtenerCamposActualizar();
            control.actualizar(docente);
            JOptionPane.showMessageDialog(panelCentral, "Docente modificado exitosamente.",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            enableComponents(panelCreacion, false);
            cargarTabla(0);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void botonModificar() {
        int codigo = seleccionTablaCodigo();
        if (codigo != -1) {
            enableComponents(panelCreacion, true);
            btnGuardar.setText("MODIFICAR");
            textoId.setEnabled(false);
            pass.setEnabled(false);
            Docente docente;
            try {
                docente = control.buscarPorCodigo(codigo);
                pintarCampos(docente);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
            }

        }
    }

    private int seleccionTablaCodigo() {
        int indice = table.getSelectedRow();
        if (indice == -1) {
            JOptionPane.showMessageDialog(panelCentral, "Seleccione un Docente!", "Validacion", JOptionPane.INFORMATION_MESSAGE);
            return -1;
        } else {
            String codigo = String.valueOf(table.getValueAt(indice, 0));
            int cod = Integer.valueOf(codigo);
            return cod;
        }
    }

    private void botonGuardar() {
        if (validarCampos()) {
            Docente docente = obtenerCampos();
            try {
                control.registrar(docente);
                JOptionPane.showMessageDialog(panelCentral, "Docente registrado exitosamente.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                enableComponents(panelCreacion, false);
                cargarTabla(0);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Validacion", JOptionPane.QUESTION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panelCentral, ex.getMessage(), "Excepcion", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panelCentral, "Verifique los campos", "Validacion", JOptionPane.QUESTION_MESSAGE);
        }

    }

    private Docente obtenerCampos() {
        Docente docente;
        int codigo = Integer.parseInt(labelCodigo.getText());
        String identificacion = textoId.getText();
        String nombres = textoNombre.getText().toUpperCase();
        String apellidos = textoApellidos.getText().toUpperCase();
        String direccion = textoDireccion.getText();
        String correo = textoCorreo.getText();
        String telefono = textoTelefono.getText();
        String titulo = textoTitulo.getText();
        String ciudad = textoCiudad.getText();
        Long fecha = calendarFecha.getDate().getTime();
        //
        Date fechaNacimiento = new Date(fecha);
        int tipoSangre = comboTipoSangre.getSelectedIndex();
        int estado = comboEstado.getSelectedIndex();
        String password = String.valueOf(pass.getPassword());

        Usuario usuario = new Usuario(identificacion, nombres, password, 2);
        docente = new Docente(codigo, nombres, apellidos, estado, fechaNacimiento, tipoSangre, direccion,
                telefono, correo, ciudad, titulo, usuario);

        return docente;

    }

    private Docente obtenerCamposActualizar() {
        int codigo = Integer.parseInt(labelCodigo.getText());

        try {
            Docente docente;
            docente = control.buscarPorCodigo(codigo);
            docente.setNombres(textoNombre.getText().toUpperCase());
            docente.setApellidos(textoApellidos.getText().toUpperCase());
            docente.setDireccion(textoDireccion.getText());
            docente.setCorreo(textoCorreo.getText());
            docente.setTelefono(textoTelefono.getText());
            docente.setTitulo(textoTitulo.getText());
            docente.setCiudad(textoCiudad.getText());

            Long fecha = calendarFecha.getDate().getTime();
            Date fechaNacimiento = new Date(fecha);

            docente.setFechaNacimiento(fechaNacimiento);
            docente.setTipoSangre(comboTipoSangre.getSelectedIndex());
            docente.setEstado(comboEstado.getSelectedIndex());

            return docente;
        } catch (Exception ex) {
            Logger.getLogger(ViewDocente.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    private void pintarCampos(Docente docente) {
        labelCodigo.setText("" + docente.getIdDocente());
        textoId.setText("" + docente.getUsuario().getCodigo());
        textoNombre.setText(docente.getNombres());
        textoApellidos.setText(docente.getApellidos());
        textoCiudad.setText(docente.getCiudad());
        textoCorreo.setText(docente.getCorreo());
        textoTitulo.setText(docente.getTitulo());
        textoDireccion.setText(docente.getDireccion());
        textoTelefono.setText(docente.getTelefono());
        calendarFecha.setDate(docente.getFechaNacimiento());
        comboEstado.setSelectedIndex(docente.getEstado());
        comboTipoSangre.setSelectedIndex(docente.getTipoSangre());

    }

    private boolean validarCampos() {

        if (textoId.getText().equals("")) {
            return false;
        }
        if (textoNombre.getText().equals("")) {
            return false;
        }
        if (textoApellidos.getText().equals("")) {
            return false;
        }
        if (pass.getText().equals("")) {
            return false;
        }
        try {
            if (calendarFecha.getDate() == null) {
                return false;
            }
        } catch (Exception e) {
            return false;
        }

        return true;
    }

    private void limpiarCampos() {
        labelCodigo.setText("0");
        textoId.setText("");
        textoNombre.setText("");
        textoApellidos.setText("");
        textoCiudad.setText("");
        textoCorreo.setText("");
        textoTitulo.setText("");
        textoDireccion.setText("");
        textoTelefono.setText("");
        pass.setText("");
        comboEstado.setSelectedIndex(0);
        comboTipoSangre.setSelectedIndex(0);
    }

    public void enableComponents(Container container, boolean enable) {

        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                enableComponents((Container) component, enable);
            }
        }
    }

    private void filtro(String consulta, JTable jtableBuscar) {
        DefaultTableModel dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private com.toedter.calendar.JDateChooser calendarFecha;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JComboBox<String> comboTipoSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelCreacion;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTable table;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JTextField textoCiudad;
    private javax.swing.JTextField textoCorreo;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoFiltro;
    private javax.swing.JTextField textoId;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    private javax.swing.JTextField textoTitulo;
    // End of variables declaration//GEN-END:variables
}
